-- AlterTable
ALTER TABLE "User" ADD COLUMN     "caloriesTarget" INTEGER NOT NULL DEFAULT 2000,
ADD COLUMN     "carbs" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "fat" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "protein" DOUBLE PRECISION DEFAULT 0.0,
ADD COLUMN     "sugar" DOUBLE PRECISION DEFAULT 0.0;
